export const CATEGORIES = {
  all: "Все",
  reclama: "Реклама",
  docReclama: "Документальная_реклама",
  korpVideo: "Корпоративное_видео",
  FPV: "FPV-съемка",
  graph: "Графика",
  docKino: "Документальное_кино",
  clip: "Клипы",
  showreel: "Шоурилы",
};

export const TAGS = {
  showreel: "showreel",
  tv: "TV",
  FPV: "FPV",
  // olv: "OLV",
  // clv: "CLV",
  food: "food",
  korp: "корпоративное",
  CG: "CG",
  clip: "клип",
  docKino: "док",
  opening: "opening",
  threeD: "3D",
  // VFX: "VFX",
  // NFT: "NFT",
  digital: "digital",
  // hr: "HR-ролики",
  // pres: "презентации",
  aero: "аэросъемка",
  // extrim: "экстрим",
  // show: "шоу",
  // web: "веб-сериалы",
  // almanah: "альманахи",
  // snippet: "сниппеты",
  // film: "фильмы",
  // visit: "визитки",
  // live: "лайвы",
  promo: "promo",
  // explay: "эксплейнеры",
};
