import { CATEGORIES, TAGS } from "./filters";

export const videoList = [
  {
    localUrl: "showreel",
    vimeoUrl: "https://player.vimeo.com/video/687465086?h=100169ac7e",
    category: CATEGORIES.showreel,
    tags: [TAGS.showreel],
    label: "SHOWREEL 2021",
    poster: "showreel-port-poster.png",
  },
  {
    localUrl: "cg",
    vimeoUrl: "https://player.vimeo.com/video/788918951?h=7d993bb16e",
    category: CATEGORIES.showreel,
    tags: [TAGS.showreel],
    label: "GRAPHICS SHOWREEL 2022",
    poster: "cg-poster.png",
  },
  {
    localUrl: "fpv-showreel",
    vimeoUrl: "https://player.vimeo.com/video/759451849?h=813dd51b71",
    category: CATEGORIES.showreel,
    tags: [TAGS.showreel],
    label: "FPV SHOWREEL 2021",
    poster: "fpv-showreel-poster.jpeg",
  },
  {
    localUrl: "polemica",
    vimeoUrl: "https://player.vimeo.com/video/787493399?h=677c053041",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital],
    label: "Polemica / Promo video",
    poster: "polemica-poster.png",
  },
  {
    localUrl: "tingz",
    vimeoUrl: "https://player.vimeo.com/video/787493426?h=36c3c825fd",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital],
    label: "Tingz / Promo video",
    poster: "tingz-poster.png",
  },
  {
    localUrl: "izum",
    vimeoUrl: "https://player.vimeo.com/video/528187039?h=e8e420bfc5",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.tv],
    label: "Izum / TV Promo",
    poster: "izum-poster.png",
  },
  {
    localUrl: "ulibka",
    vimeoUrl: "https://player.vimeo.com/video/788918319?h=ce8a5dc86e",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.tv],
    label: "Ulybka / TV Ad",
    poster: "ulibka-poster.png",
  },
  {
    localUrl: "sushi",
    vimeoUrl: "https://player.vimeo.com/video/528189934?h=b0d1b705ef",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital, TAGS.food],
    label: "Sushi-Market / Food video",
    poster: "sushi-poster.png",
  },
  {
    localUrl: "moretv",
    vimeoUrl: "https://player.vimeo.com/video/794151930?h=d6d0e713f5",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital],
    label: "More.tv / Teaser",
    poster: "moretv-poster.png",
  },

  {
    localUrl: "linkin",
    vimeoUrl: "https://player.vimeo.com/video/526066864?h=385e933002",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital],
    label: "Linkin.Park / Promo",
    poster: "linkin-poster.png",
  },
  {
    localUrl: "eurasia",
    vimeoUrl: "https://player.vimeo.com/video/759451596?h=377a4bd074",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.tv, TAGS.food],
    label: "Eurasia Bar / Food",
    poster: "eurasia-poster.png",
  },
  {
    localUrl: "rusich",
    vimeoUrl: "https://player.vimeo.com/video/528193680?h=dd753025e0",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital],
    label: "Rusich / New Collection",
    poster: "rusich-poster.png",
  },
  {
    localUrl: "lavash",
    vimeoUrl: "https://player.vimeo.com/video/526077604?h=9197b41ff0",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital, TAGS.threeD, TAGS.CG],
    label: "Lavash / Promo",
    poster: "lavash-poster.png",
  },
  {
    localUrl: "almaz",
    vimeoUrl: "https://player.vimeo.com/video/473069700?h=acedeb1c97",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.tv],
    label: "Almazny Zal / TV Promo",
    poster: "almaz-poster.png",
  },
  {
    localUrl: "dom",
    vimeoUrl: "https://player.vimeo.com/video/759499744?h=55e5aefc8d",
    category: CATEGORIES.docKino,
    tags: [TAGS.docKino, TAGS.aero, TAGS.FPV],
    label: "Там, где наш дом / Трейлер",
    poster: "dom-poster.png",
  },
  {
    localUrl: "olymp",
    vimeoUrl: "https://player.vimeo.com/video/831151211?h=c23d542973",
    category: CATEGORIES.docKino,
    tags: [TAGS.docKino, TAGS.aero, TAGS.FPV],
    label: "Улицы Олимпийского резерва / Трейлер",
    poster: "olymp-poster.jpg",
  },
  {
    localUrl: "poezd",
    vimeoUrl: "https://player.vimeo.com/video/831154612?h=b8c89f077c",
    category: CATEGORIES.docKino,
    tags: [TAGS.docKino, TAGS.aero, TAGS.FPV],
    label: "Нескорый поезд / Трейлер",
    poster: "poezd-poster.png",
  },
  {
    localUrl: "nauka",
    vimeoUrl: "https://player.vimeo.com/video/687466644?h=f3c4ff2a6d",
    category: CATEGORIES.docKino,
    tags: [TAGS.docKino, TAGS.threeD, TAGS.CG],
    label: "Займемся наукой. Биоинженерия / Трейлер",
    poster: "nauka-poster.png",
  },
  {
    localUrl: "nezav",
    vimeoUrl: "https://player.vimeo.com/video/788917697?h=3077e2e530",
    category: CATEGORIES.docKino,
    tags: [TAGS.docKino, TAGS.aero, TAGS.FPV, TAGS.threeD, TAGS.CG],
    label: "Игровая независимость / Трейлер",
    poster: "nezav-poster.png",
  },
  {
    localUrl: "gayane",
    vimeoUrl: "https://player.vimeo.com/video/787493279?h=8689c9f2e4",
    category: CATEGORIES.docReclama,
    tags: [TAGS.docKino, TAGS.digital, TAGS.korp],
    label: "Yandex Go - Gayane / Doc commercial",
    poster: "gayane-poster.png",
  },
  {
    localUrl: "victor",
    vimeoUrl: "https://player.vimeo.com/video/787492863?h=aa6bf236a1",
    category: CATEGORIES.docReclama,
    tags: [TAGS.docKino, TAGS.digital, TAGS.korp],
    label: "Yandex Go - Victor / Doc commercial",
    poster: "victor-poster.png",
  },
  {
    localUrl: "ctrl-cometa",
    vimeoUrl: "https://player.vimeo.com/video/759443253?h=6817228d65",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "Ctrl+A / Music video",
    poster: "ctrl-cometa-poster.png",
  },
  {
    localUrl: "dose",
    vimeoUrl: "https://player.vimeo.com/video/787493181?h=4492bb78da",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "Dose - Потеряли / Music video",
    poster: "dose-poster.png",
  },
  {
    localUrl: "ctrl",
    vimeoUrl: "https://player.vimeo.com/video/788917724?h=8cb68bdf9b",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "CTRL+A - Add / Music video",
    poster: "ctrl-poster.png",
  },
  {
    localUrl: "bums",
    vimeoUrl: "https://player.vimeo.com/video/787492995?h=ce79719d2a",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "STILL BUMS / Music video",
    poster: "bums-poster.png",
  },
  {
    localUrl: "love",
    vimeoUrl: "https://player.vimeo.com/video/788555596?h=43835812c7",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "Random Love / Music video",
    poster: "love-poster.png",
  },
  {
    localUrl: "myqeed",
    vimeoUrl: "https://player.vimeo.com/video/794151997?h=6cc32911eb",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "MYQEED / Snippet",
    poster: "myqeed-poster.png",
  },
  {
    localUrl: "narcissus",
    vimeoUrl: "https://player.vimeo.com/video/831158837?h=97ac7ea687",
    category: CATEGORIES.clip,
    tags: [TAGS.clip],
    label: "The Story of Narcissus / Dance shot",
    poster: "narcissus-poster.png",
  },
  {
    localUrl: "oemz",
    vimeoUrl: "https://player.vimeo.com/video/473066006?h=a36868cc09",
    category: CATEGORIES.korpVideo,
    tags: [TAGS.korp],
    label: "OEMZ / Corporate video",
    poster: "oemz-poster.png",
  },
  {
    localUrl: "rt",
    vimeoUrl: "https://player.vimeo.com/video/759451797?h=cf795c130a",
    category: CATEGORIES.korpVideo,
    tags: [TAGS.korp, TAGS.aero, TAGS.FPV],
    label: "RT / Corporate video",
    poster: "rt-poster.png",
  },
  {
    localUrl: "softline",
    vimeoUrl: "https://player.vimeo.com/video/788922347?h=6291ea4d19",
    category: CATEGORIES.korpVideo,
    tags: [TAGS.korp, TAGS.aero],
    label: "Softline / Corporate video",
    poster: "softline-poster.png",
  },
  {
    localUrl: "tool",
    vimeoUrl: "https://player.vimeo.com/video/831173678?h=6d095f3b2",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital, TAGS.korp],
    label: "Silbertool / 3D",
    poster: "tool-poster.png",
  },
  {
    localUrl: "mega",
    vimeoUrl: "https://player.vimeo.com/video/788917875?h=74e9fd37e9",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital],
    label: "MEGA / Graphics",
    poster: "mega-poster.png",
  },
  {
    localUrl: "them",
    vimeoUrl: "https://player.vimeo.com/video/790835890?h=48b77c349a",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital],
    label: "THEM / 3D product",
    poster: "them-poster.png",
  },
  {
    localUrl: "zemlya",
    vimeoUrl: "https://player.vimeo.com/video/790835952?h=9b525cf818",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.opening],
    label: "Zemlya 2030 / 3D oppening",
    poster: "zemlya-poster.png",
  },
  {
    localUrl: "borodina",
    vimeoUrl: "https://player.vimeo.com/video/790835696?h=ff0470ecdd",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.opening],
    label: "Borodina / 3D oppening",
    poster: "borodina-poster.png",
  },
  {
    localUrl: "vzyatki",
    vimeoUrl: "https://player.vimeo.com/video/790835923?h=40d143eb38",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.opening],
    label: "Vzyatki / 3D oppening",
    poster: "vzyatki-poster.png",
  },
  {
    localUrl: "nft",
    vimeoUrl: "https://player.vimeo.com/video/790838242?h=e6a073fad6",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital],
    label: "NFT Collection / 3D",
    poster: "nft-poster.png",
  },
  {
    localUrl: "rizolin-city",
    vimeoUrl: "https://player.vimeo.com/video/788918262?h=0d3f42e6d5",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital, TAGS.korp],
    label: "Rizolin (city) / 3D",
    poster: "rizolin-city-poster.png",
  },
  {
    localUrl: "rizolin",
    vimeoUrl: "https://player.vimeo.com/video/788918146?h=393df4d3ae",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.digital, TAGS.korp],
    label: "Rizolin / 3D",
    poster: "rizolin-poster.png",
  },
  {
    localUrl: "cyber",
    vimeoUrl: "https://player.vimeo.com/video/790835858?h=dcea60256f",
    category: CATEGORIES.graph,
    tags: [TAGS.threeD, TAGS.opening],
    label: "Cyber ethics / 3D oppening",
    poster: "cyber-poster.png",
  },
  {
    localUrl: "hand",
    vimeoUrl: "https://player.vimeo.com/video/790835806?h=a8c91d8b51",
    category: CATEGORIES.graph,
    tags: [TAGS.CG, TAGS.threeD],
    label: "Cyber hand / 3D",
    poster: "hand-poster.png",
  },

  {
    localUrl: "multispace",
    vimeoUrl: "https://player.vimeo.com/video/831162582?h=07b9e0f26d",
    category: CATEGORIES.graph,
    tags: [TAGS.korp],
    label: "Multispace / Infographics",
    poster: "multispace-poster.png",
  },
  {
    localUrl: "vokzal",
    vimeoUrl: "https://player.vimeo.com/video/788557268?h=4f77c6281c",
    category: CATEGORIES.FPV,
    tags: [TAGS.promo, TAGS.aero, TAGS.FPV, TAGS.CG],
    label: "VOKZAL 1853 / FPV",
    poster: "vokzal-poster.png",
  },
  {
    localUrl: "ciay",
    vimeoUrl: "https://player.vimeo.com/video/794562118?h=b6d3fd91c5",
    category: CATEGORIES.FPV,
    tags: [TAGS.promo, TAGS.aero, TAGS.FPV],
    label: "CIAY MOTOCROSS / Strokov David",
    poster: "ciay-poster.png",
  },
  {
    localUrl: "asber",
    vimeoUrl: "https://player.vimeo.com/video/788557227?h=c010f977b1",
    category: CATEGORIES.FPV,
    tags: [TAGS.promo, TAGS.aero, TAGS.FPV, TAGS.CG],
    label: "Asber / FPV",
    poster: "asber-poster.png",
  },
  {
    localUrl: "living-display",
    vimeoUrl: "https://player.vimeo.com/video/533567798?h=1d0b860b90",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital, TAGS.threeD],
    label: "Living Skog (Display Storage) / Marketplace video",
    poster: "living-display-poster.png",
  },
  {
    localUrl: "living-cabinet",
    vimeoUrl: "https://player.vimeo.com/video/533564479?h=7be9544353",
    category: CATEGORIES.reclama,
    tags: [TAGS.promo, TAGS.digital, TAGS.threeD],
    label: "Living Skog (Cabinet) / Marketplace video",
    poster: "living-cabinet-poster.png",
  },
  {
    localUrl: "baggins",
    vimeoUrl: "https://player.vimeo.com/video/788739813?h=268e0b3bc5",
    category: CATEGORIES.reclama,
    tags: [],
    label: "BAGGINS COFFEE / Promo",
    poster: "baggins-poster.png",
  },
];
